---

- name: Upgrade system packages
  package:
    name: "*"
    state: latest

- name: Install minimal packages
  package:
    name: "{{ pre_install_package }}"
    state: present

- name: Set timezone
  timezone:
    name: "{{ timezone }}"