pre_install_packages:
  - epel-release
  - firewalld
  - vim
  - yum-utils
  - iproute-tc
  - zip
  - tar

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

cilium_tcp:
  - "4240" # health checks
  - "4044-4045" # Hubble server/relay
  - "2379-2380" # etcd access
  - "6060-6062" # cilium-agent pprof server / cilium-operator pprof server / Hubble Relay pprof server 
  - "6942" # operator Prometheus metrics
  - "9090" # cilium-agent Prometheus metrics
  - "9876" # cilium-agent health status API
  - "9890-9893" # cilium-agent gops server / operator gops server /  	clustermesh-apiserver gops server / Hubble Relay gops server

cilium_udp:
  - "4240" # health checks
  - "8472" # VXLAN overlay
  - "51871" # WireGuard encryption tunnel endpoint

cilium_params:
  - CONFIG_BPF=y
  - CONFIG_BPF_SYSCALL=y
  - CONFIG_NET_CLS_BPF=y
  - CONFIG_BPF_JIT=y
  - CONFIG_NET_CLS_ACT=y
  - CONFIG_NET_SCH_INGRESS=y
  - CONFIG_CRYPTO_SHA1=y
  - CONFIG_CRYPTO_USER_API_HASH=y
  - CONFIG_CGROUPS=y
  - CONFIG_CGROUP_BPF=y
  - CONFIG_NETFILTER_XT_SET=m
  - CONFIG_IP_SET=m
  - CONFIG_IP_SET_HASH_IP=m
  - CONFIG_NETFILTER_XT_TARGET_TPROXY=m
  - CONFIG_NETFILTER_XT_TARGET_CT=m
  - CONFIG_NETFILTER_XT_MATCH_MARK=m
  - CONFIG_NETFILTER_XT_MATCH_SOCKET=m
  - CONFIG_NET_SCH_FQ=m

firewall_standard:
  - 80
  - 443

## 9153/tcp ??