---

#- name: Set permanent cilium params
#  template:
#    src: environment.j2
#    dest: /etc/environment
#    mode: 0644

#- name: Set dynamic cilium params
#  shell: "export {{ item }}"
#  with_items: "{{ cilium_params }}"

#- name: Add cilium repo
#  shell: helm repo add cilium https://helm.cilium.io/

#- name: Install cilium
#  shell: |
#    helm install cilium cilium/cilium --version 1.11.5 \
#      --namespace kube-system \
#      --set ipam.operator.clusterPoolIPv4PodCIDR="10.244.0.0/16" \
#      --set global.masquerade=false \
#      --set global.nodeinit.enabled=true \
#      --set hostFirewall.enabled=true \
#      --set bandwidthManager=true \
#      --set enableXTSocketFallback=false \
#      --set kubeProxyReplacement=strict \
#      --set hubble.enabled=false \
#      --set encryption.enabled=true
#    until [[ $(kubectl get pods -n kube-system --field-selector status.phase!=Running | wc -l) == 0 ]] ; do date; sleep 1; echo ""; done
#    sleep 10

- name: Install minimal packages
  package:
    name: "{{ cilium_pkg_require }}"
    state: present

- name: Set permanent cilium params
  template:
    src: environment.j2
    dest: /etc/environment
    mode: 0644

- name: Set dynamic cilium params
  shell: "export {{ item }}"
  with_items: "{{ cilium_params }}"

- name: Get latest cilium cli version
  uri:
    url: https://api.github.com/repos/cilium/cilium-cli/releases/latest
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  register: ciliumcli_version

- set_fact:
    ciliumcli_tag: "{{ ciliumcli_version['json']['tag_name'] }}"

- name: Download clilium
  unarchive:
    src: "https://github.com/cilium/cilium-cli/releases/download/{{ ciliumcli_tag }}/cilium-linux-amd64.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
  retries: 3

- name: Install cilium
  shell: cilium install
  retries: 3