---

- name: Kubernetes API server
  firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: inventory_hostname in groups['k8s_masters']

- name: Etcd server client API
  firewalld:
    port: 2379-2380/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: inventory_hostname in groups['k8s_masters']

- name: Kubelet API
  firewalld:
    port: 10250/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: inventory_hostname in groups['k8s_masters'] or inventory_hostname in groups['k8s_nodes']

- name: Kube-scheduler
  firewalld:
    port: 10259/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: inventory_hostname in groups['k8s_masters']

- name: Kube-controller-manager
  firewalld:
    port: 10257/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: inventory_hostname in groups['k8s_masters']

- name: KubeletAPI
  firewalld:
    port: 30000-32767/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: inventory_hostname in groups['k8s_nodes']

- name: Allow masquerade
  firewalld:
      masquerade: yes
      state: enabled
      permanent: yes

#- name: Calico Typha
#  firewalld:
#    port: 5473/tcp
#    permanent: yes
#    state: enabled
#    immediate: yes

#- name: Calico VXLAN
#  firewalld:
#    port: 4789/udp
#    permanent: yes
#    state: enabled
#    immediate: yes

- name: HTTPS
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: HTTP
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: DNS TCP
  firewalld:
    port: 53/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: DNS UDP
  firewalld:
    port: 53/udp
    permanent: yes
    state: enabled
    immediate: yes

#- name: Calico BGP
#  firewalld:
#    port: 179/tcp
#    permanent: yes
#    state: enabled
#    immediate: yes

- name: Cilium TCP
  firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "{{ cilium_tcp }}"

- name: Cilium UDP
  firewalld:
    port: "{{ item }}/udp"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - "{{ cilium_udp }}"

- name: MetaLB UDP
  firewalld:
    port: 7946/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: MetaLB TCP
  firewalld:
    port: 7946/udp
    permanent: yes
    state: enabled
    immediate: yes

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
    enabled: yes
