---

#- name: Create path
#  file:
#    path : "{{ kubernetes_project_path }}"
#    state: directory
#    mode: 0755

- name: Check Helm3
  stat:
    path: /usr/local/bin/helm
  register: helm3_status

- name: Download Helm3
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh 
    mode: 0755
  when: not helm3_status.stat.exists

- name: Install Helm3
  shell: bash /tmp/get_helm.sh
  when: not helm3_status.stat.exists
