---

# hostnamectl set-hostname nom_machine
#- name: Set hostname
#  hostname:
#    name: "{{ item }}{{ index }}"
#  loop: "{{ groups['k8s_nodes'] }}"
#  loop_control:
#    index_var: index
#  when: inventory_hostname in groups['k8s_nodes']

- name: Configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts