---

- name: Enable br_netfilter and overlay modprobe
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Copy kubernetes cri configuration
  copy:
    src: 99-kubernetes-cri.conf
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    owner: root
    group: root

- name: Reload sysctl system
  command: sysctl --system
