---

- name: Open HTTP API / RPC / serf WAN TCP
  firewalld:
    port: 4646-4648/tcp
    permanent: yes
    state: enabled

- name: Open serf WAN UDP
  firewalld:
    port: 4648/udp
    permanent: yes
    state: enabled
  notify:
    - Reload firewalld

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded