---

- name: Copy nomad bridge network configuration
  copy:
    src: 99-nomad.conf
    dest: /etc/sysctl.d/99-nomad.conf
    owner: root
    group: root

- name: Reload sysctl system
  command: sysctl --system
